# Generated by Django 4.1.7 on 2023-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
