# Generated by Django 4.1.7 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
